In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/gaurav9712/50-startups/50_Startups.csv

In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
df = np.round(pd.read_csv('/kaggle/input/datasets/gaurav9712/50-startups/50_Startups.csv'))[['R&D Spend','Administration','Marketing Spend','Profit']]
np.random.seed(9)
df

    R&D Spend  Administration  Marketing Spend    Profit
0    165349.0        136898.0         471784.0  192262.0
1    162598.0        151378.0         443899.0  191792.0
2    153442.0        101146.0         407935.0  191050.0
3    144372.0        118672.0         383200.0  182902.0
4    142107.0         91392.0         366168.0  166188.0
5    131877.0         99815.0         362861.0  156991.0
6    134615.0        147199.0         127717.0  156123.0
7    130298.0        145530.0         323877.0  155753.0
8    120543.0        148719.0         311613.0  152212.0
9    123335.0        108679.0         304982.0  149760.0
10   101913.0        110594.0         229161.0  146122.0
11   100672.0         91791.0         249745.0  144259.0
12    93864.0        127320.0         249839.0  141586.0
13    91992.0        135495.0         252665.0  134307.0
14   119943.0        156547.0         256513.0  132603.0
15   114524.0        122617.0         261776.0  129917.0
16    78013.0        121598.0         264346.0  126993.0
17    94657.0        145078.0         282574.0  125370.0
18    91749.0        114176.0         294920.0  124267.0
19    86420.0        153514.0              0.0  122777.0
20    76254.0        113867.0         298664.0  118474.0
21    78389.0        153773.0         299737.0  111313.0
22    73995.0        122783.0         303319.0  110352.0
23    67533.0        105751.0         304769.0  108734.0
24    77044.0         99281.0         140575.0  108552.0
25    64665.0        139553.0         137963.0  107404.0
26    75329.0        144136.0         134050.0  105734.0
27    72108.0        127865.0         353184.0  105008.0
28    66052.0        182646.0         118148.0  103282.0
29    65605.0        153032.0         107138.0  101005.0
30    61994.0        115641.0          91131.0   99938.0
31    61136.0        152702.0          88218.0   97484.0
32    63409.0        129220.0          46085.0   97428.0
33    55494.0        103057.0         214635.0   96779.0
34    46426.0        157694.0         210798.0   96713.0
35    46014.0         85047.0         205518.0   96480.0
36    28664.0        127056.0         201127.0   90708.0
37    44070.0         51283.0         197029.0   89949.0
38    20230.0         65948.0         185265.0   81229.0
39    38559.0         82982.0         174999.0   81006.0
40    28754.0        118546.0         172796.0   78240.0
41    27893.0         84711.0         164471.0   77799.0
42    23641.0         96190.0         148001.0   71498.0
43    15506.0        127382.0          35534.0   69759.0
44    22178.0        154806.0          28335.0   65200.0
45     1000.0        124153.0           1904.0   64926.0
46     1315.0        115816.0         297114.0   49491.0
47        0.0        135427.0              0.0   42560.0
48      542.0         51743.0              0.0   35673.0
49        0.0        116984.0          45173.0   14681.0

In [4]:
df = df.iloc[:, 0:-1]
df

    R&D Spend  Administration  Marketing Spend
0    165349.0        136898.0         471784.0
1    162598.0        151378.0         443899.0
2    153442.0        101146.0         407935.0
3    144372.0        118672.0         383200.0
4    142107.0         91392.0         366168.0
5    131877.0         99815.0         362861.0
6    134615.0        147199.0         127717.0
7    130298.0        145530.0         323877.0
8    120543.0        148719.0         311613.0
9    123335.0        108679.0         304982.0
10   101913.0        110594.0         229161.0
11   100672.0         91791.0         249745.0
12    93864.0        127320.0         249839.0
13    91992.0        135495.0         252665.0
14   119943.0        156547.0         256513.0
15   114524.0        122617.0         261776.0
16    78013.0        121598.0         264346.0
17    94657.0        145078.0         282574.0
18    91749.0        114176.0         294920.0
19    86420.0        153514.0              0.0
20    76254.0        113867.0         298664.0
21    78389.0        153773.0         299737.0
22    73995.0        122783.0         303319.0
23    67533.0        105751.0         304769.0
24    77044.0         99281.0         140575.0
25    64665.0        139553.0         137963.0
26    75329.0        144136.0         134050.0
27    72108.0        127865.0         353184.0
28    66052.0        182646.0         118148.0
29    65605.0        153032.0         107138.0
30    61994.0        115641.0          91131.0
31    61136.0        152702.0          88218.0
32    63409.0        129220.0          46085.0
33    55494.0        103057.0         214635.0
34    46426.0        157694.0         210798.0
35    46014.0         85047.0         205518.0
36    28664.0        127056.0         201127.0
37    44070.0         51283.0         197029.0
38    20230.0         65948.0         185265.0
39    38559.0         82982.0         174999.0
40    28754.0        118546.0         172796.0
41    27893.0         84711.0         164471.0
42    23641.0         96190.0         148001.0
43    15506.0        127382.0          35534.0
44    22178.0        154806.0          28335.0
45     1000.0        124153.0           1904.0
46     1315.0        115816.0         297114.0
47        0.0        135427.0              0.0
48      542.0         51743.0              0.0
49        0.0        116984.0          45173.0

In [5]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan
df.head()

/tmp/ipykernel_16/1429726703.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.nan
/tmp/ipykernel_16/1429726703.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.nan
/tmp/ipykernel_16/1429726703.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1,-1] = np.nan

   R&D Spend  Administration  Marketing Spend
0   165349.0        136898.0         471784.0
1        NaN        151378.0         443899.0
2   153442.0        101146.0         407935.0
3   144372.0             NaN         383200.0
4   142107.0         91392.0         366168.0

In [6]:
#Step 1 - Impute all missing values with mean of respective columns
df0 = pd.DataFrame()
df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [7]:
#0th Iteration
df0

        R&D Spend  Administration  Marketing Spend
0   165349.000000   136898.000000    471784.000000
1    71907.836735   151378.000000    443899.000000
2   153442.000000   101146.000000    407935.000000
3   144372.000000   121399.204082    383200.000000
4   142107.000000    91392.000000    366168.000000
5   131877.000000    99815.000000    362861.000000
6   134615.000000   147199.000000    127717.000000
7   130298.000000   145530.000000    323877.000000
8   120543.000000   148719.000000    311613.000000
9   123335.000000   108679.000000    304982.000000
10  101913.000000   110594.000000    229161.000000
11  100672.000000    91791.000000    249745.000000
12   93864.000000   127320.000000    249839.000000
13   91992.000000   135495.000000    252665.000000
14  119943.000000   156547.000000    256513.000000
15  114524.000000   122617.000000    261776.000000
16   78013.000000   121598.000000    264346.000000
17   94657.000000   145078.000000    282574.000000
18   91749.000000   114176.000000    294920.000000
19   86420.000000   153514.000000         0.000000
20   76254.000000   113867.000000    298664.000000
21   78389.000000   153773.000000    299737.000000
22   73995.000000   122783.000000    303319.000000
23   67533.000000   105751.000000    304769.000000
24   77044.000000    99281.000000    140575.000000
25   64665.000000   139553.000000    137963.000000
26   75329.000000   144136.000000    134050.000000
27   72108.000000   127865.000000    353184.000000
28   66052.000000   182646.000000    118148.000000
29   65605.000000   153032.000000    107138.000000
30   61994.000000   115641.000000     91131.000000
31   61136.000000   152702.000000     88218.000000
32   63409.000000   129220.000000     46085.000000
33   55494.000000   103057.000000    214635.000000
34   46426.000000   157694.000000    210798.000000
35   46014.000000    85047.000000    205518.000000
36   28664.000000   127056.000000    201127.000000
37   44070.000000    51283.000000    197029.000000
38   20230.000000    65948.000000    185265.000000
39   38559.000000    82982.000000    174999.000000
40   28754.000000   118546.000000    172796.000000
41   27893.000000    84711.000000    164471.000000
42   23641.000000    96190.000000    148001.000000
43   15506.000000   127382.000000     35534.000000
44   22178.000000   154806.000000     28335.000000
45    1000.000000   124153.000000      1904.000000
46    1315.000000   115816.000000    297114.000000
47       0.000000   135427.000000         0.000000
48     542.000000    51743.000000         0.000000
49       0.000000   116984.000000    214409.836735

In [8]:
# Remove thr col 1 imputed value
df1 = df0.copy()
df1.iloc[1,0] = np.nan
df1

    R&D Spend  Administration  Marketing Spend
0    165349.0   136898.000000    471784.000000
1         NaN   151378.000000    443899.000000
2    153442.0   101146.000000    407935.000000
3    144372.0   121399.204082    383200.000000
4    142107.0    91392.000000    366168.000000
5    131877.0    99815.000000    362861.000000
6    134615.0   147199.000000    127717.000000
7    130298.0   145530.000000    323877.000000
8    120543.0   148719.000000    311613.000000
9    123335.0   108679.000000    304982.000000
10   101913.0   110594.000000    229161.000000
11   100672.0    91791.000000    249745.000000
12    93864.0   127320.000000    249839.000000
13    91992.0   135495.000000    252665.000000
14   119943.0   156547.000000    256513.000000
15   114524.0   122617.000000    261776.000000
16    78013.0   121598.000000    264346.000000
17    94657.0   145078.000000    282574.000000
18    91749.0   114176.000000    294920.000000
19    86420.0   153514.000000         0.000000
20    76254.0   113867.000000    298664.000000
21    78389.0   153773.000000    299737.000000
22    73995.0   122783.000000    303319.000000
23    67533.0   105751.000000    304769.000000
24    77044.0    99281.000000    140575.000000
25    64665.0   139553.000000    137963.000000
26    75329.0   144136.000000    134050.000000
27    72108.0   127865.000000    353184.000000
28    66052.0   182646.000000    118148.000000
29    65605.0   153032.000000    107138.000000
30    61994.0   115641.000000     91131.000000
31    61136.0   152702.000000     88218.000000
32    63409.0   129220.000000     46085.000000
33    55494.0   103057.000000    214635.000000
34    46426.0   157694.000000    210798.000000
35    46014.0    85047.000000    205518.000000
36    28664.0   127056.000000    201127.000000
37    44070.0    51283.000000    197029.000000
38    20230.0    65948.000000    185265.000000
39    38559.0    82982.000000    174999.000000
40    28754.0   118546.000000    172796.000000
41    27893.0    84711.000000    164471.000000
42    23641.0    96190.000000    148001.000000
43    15506.0   127382.000000     35534.000000
44    22178.0   154806.000000     28335.000000
45     1000.0   124153.000000      1904.000000
46     1315.0   115816.000000    297114.000000
47        0.0   135427.000000         0.000000
48      542.0    51743.000000         0.000000
49        0.0   116984.000000    214409.836735

In [9]:
#Use 3 rows to build a model and use the last for prediction
x = df1.iloc[[0,2,3,4],1:3]
x

   Administration  Marketing Spend
0   136898.000000         471784.0
2   101146.000000         407935.0
3   121399.204082         383200.0
4    91392.000000         366168.0

In [10]:
y = df1.iloc[[0,2,3,4],0]
y

0    165349.0
2    153442.0
3    144372.0
4    142107.0
Name: R&D Spend, dtype: float64

In [11]:
lr = LinearRegression()
lr.fit(x, y)
predicted_val = lr.predict(df1.iloc[[1], 1:])
predicted_val

array([156865.90298703])

In [12]:
df1.iloc[3,1] = 23.14

In [13]:
df1

    R&D Spend  Administration  Marketing Spend
0    165349.0       136898.00    471784.000000
1         NaN       151378.00    443899.000000
2    153442.0       101146.00    407935.000000
3    144372.0           23.14    383200.000000
4    142107.0        91392.00    366168.000000
5    131877.0        99815.00    362861.000000
6    134615.0       147199.00    127717.000000
7    130298.0       145530.00    323877.000000
8    120543.0       148719.00    311613.000000
9    123335.0       108679.00    304982.000000
10   101913.0       110594.00    229161.000000
11   100672.0        91791.00    249745.000000
12    93864.0       127320.00    249839.000000
13    91992.0       135495.00    252665.000000
14   119943.0       156547.00    256513.000000
15   114524.0       122617.00    261776.000000
16    78013.0       121598.00    264346.000000
17    94657.0       145078.00    282574.000000
18    91749.0       114176.00    294920.000000
19    86420.0       153514.00         0.000000
20    76254.0       113867.00    298664.000000
21    78389.0       153773.00    299737.000000
22    73995.0       122783.00    303319.000000
23    67533.0       105751.00    304769.000000
24    77044.0        99281.00    140575.000000
25    64665.0       139553.00    137963.000000
26    75329.0       144136.00    134050.000000
27    72108.0       127865.00    353184.000000
28    66052.0       182646.00    118148.000000
29    65605.0       153032.00    107138.000000
30    61994.0       115641.00     91131.000000
31    61136.0       152702.00     88218.000000
32    63409.0       129220.00     46085.000000
33    55494.0       103057.00    214635.000000
34    46426.0       157694.00    210798.000000
35    46014.0        85047.00    205518.000000
36    28664.0       127056.00    201127.000000
37    44070.0        51283.00    197029.000000
38    20230.0        65948.00    185265.000000
39    38559.0        82982.00    174999.000000
40    28754.0       118546.00    172796.000000
41    27893.0        84711.00    164471.000000
42    23641.0        96190.00    148001.000000
43    15506.0       127382.00     35534.000000
44    22178.0       154806.00     28335.000000
45     1000.0       124153.00      1904.000000
46     1315.0       115816.00    297114.000000
47        0.0       135427.00         0.000000
48      542.0        51743.00         0.000000
49        0.0       116984.00    214409.836735

In [14]:
#Remove the column 2 imputed value
df1.iloc[3,1] = np.nan
df1

    R&D Spend  Administration  Marketing Spend
0    165349.0        136898.0    471784.000000
1         NaN        151378.0    443899.000000
2    153442.0        101146.0    407935.000000
3    144372.0             NaN    383200.000000
4    142107.0         91392.0    366168.000000
5    131877.0         99815.0    362861.000000
6    134615.0        147199.0    127717.000000
7    130298.0        145530.0    323877.000000
8    120543.0        148719.0    311613.000000
9    123335.0        108679.0    304982.000000
10   101913.0        110594.0    229161.000000
11   100672.0         91791.0    249745.000000
12    93864.0        127320.0    249839.000000
13    91992.0        135495.0    252665.000000
14   119943.0        156547.0    256513.000000
15   114524.0        122617.0    261776.000000
16    78013.0        121598.0    264346.000000
17    94657.0        145078.0    282574.000000
18    91749.0        114176.0    294920.000000
19    86420.0        153514.0         0.000000
20    76254.0        113867.0    298664.000000
21    78389.0        153773.0    299737.000000
22    73995.0        122783.0    303319.000000
23    67533.0        105751.0    304769.000000
24    77044.0         99281.0    140575.000000
25    64665.0        139553.0    137963.000000
26    75329.0        144136.0    134050.000000
27    72108.0        127865.0    353184.000000
28    66052.0        182646.0    118148.000000
29    65605.0        153032.0    107138.000000
30    61994.0        115641.0     91131.000000
31    61136.0        152702.0     88218.000000
32    63409.0        129220.0     46085.000000
33    55494.0        103057.0    214635.000000
34    46426.0        157694.0    210798.000000
35    46014.0         85047.0    205518.000000
36    28664.0        127056.0    201127.000000
37    44070.0         51283.0    197029.000000
38    20230.0         65948.0    185265.000000
39    38559.0         82982.0    174999.000000
40    28754.0        118546.0    172796.000000
41    27893.0         84711.0    164471.000000
42    23641.0         96190.0    148001.000000
43    15506.0        127382.0     35534.000000
44    22178.0        154806.0     28335.000000
45     1000.0        124153.0      1904.000000
46     1315.0        115816.0    297114.000000
47        0.0        135427.0         0.000000
48      542.0         51743.0         0.000000
49        0.0        116984.0    214409.836735

In [15]:
#use the last 3 rows to build a model and use the first for the prediction
x = df1.iloc[[0,1,2,4],[0,2]]
x

   R&D Spend  Marketing Spend
0   165349.0         471784.0
1        NaN         443899.0
2   153442.0         407935.0
4   142107.0         366168.0

In [16]:
y = df1.iloc[[0,1,2,4],1]
y

0    136898.0
1    151378.0
2    101146.0
4     91392.0
Name: Administration, dtype: float64

In [17]:
x.iloc[1, 0] = 156865.90298703
lr = LinearRegression()
lr.fit(x, y)
predicted_val = lr.predict(df1.iloc[[3], [0, 2]])
predicted_val

array([114031.94116766])

In [18]:
df1.iloc[3,1] = 11.06

In [19]:
df1

    R&D Spend  Administration  Marketing Spend
0    165349.0       136898.00    471784.000000
1         NaN       151378.00    443899.000000
2    153442.0       101146.00    407935.000000
3    144372.0           11.06    383200.000000
4    142107.0        91392.00    366168.000000
5    131877.0        99815.00    362861.000000
6    134615.0       147199.00    127717.000000
7    130298.0       145530.00    323877.000000
8    120543.0       148719.00    311613.000000
9    123335.0       108679.00    304982.000000
10   101913.0       110594.00    229161.000000
11   100672.0        91791.00    249745.000000
12    93864.0       127320.00    249839.000000
13    91992.0       135495.00    252665.000000
14   119943.0       156547.00    256513.000000
15   114524.0       122617.00    261776.000000
16    78013.0       121598.00    264346.000000
17    94657.0       145078.00    282574.000000
18    91749.0       114176.00    294920.000000
19    86420.0       153514.00         0.000000
20    76254.0       113867.00    298664.000000
21    78389.0       153773.00    299737.000000
22    73995.0       122783.00    303319.000000
23    67533.0       105751.00    304769.000000
24    77044.0        99281.00    140575.000000
25    64665.0       139553.00    137963.000000
26    75329.0       144136.00    134050.000000
27    72108.0       127865.00    353184.000000
28    66052.0       182646.00    118148.000000
29    65605.0       153032.00    107138.000000
30    61994.0       115641.00     91131.000000
31    61136.0       152702.00     88218.000000
32    63409.0       129220.00     46085.000000
33    55494.0       103057.00    214635.000000
34    46426.0       157694.00    210798.000000
35    46014.0        85047.00    205518.000000
36    28664.0       127056.00    201127.000000
37    44070.0        51283.00    197029.000000
38    20230.0        65948.00    185265.000000
39    38559.0        82982.00    174999.000000
40    28754.0       118546.00    172796.000000
41    27893.0        84711.00    164471.000000
42    23641.0        96190.00    148001.000000
43    15506.0       127382.00     35534.000000
44    22178.0       154806.00     28335.000000
45     1000.0       124153.00      1904.000000
46     1315.0       115816.00    297114.000000
47        0.0       135427.00         0.000000
48      542.0        51743.00         0.000000
49        0.0       116984.00    214409.836735

In [20]:
#Remove the column 3 imputed value
df1.iloc[4,-1] = np.nan
df1

    R&D Spend  Administration  Marketing Spend
0    165349.0       136898.00    471784.000000
1         NaN       151378.00    443899.000000
2    153442.0       101146.00    407935.000000
3    144372.0           11.06    383200.000000
4    142107.0        91392.00              NaN
5    131877.0        99815.00    362861.000000
6    134615.0       147199.00    127717.000000
7    130298.0       145530.00    323877.000000
8    120543.0       148719.00    311613.000000
9    123335.0       108679.00    304982.000000
10   101913.0       110594.00    229161.000000
11   100672.0        91791.00    249745.000000
12    93864.0       127320.00    249839.000000
13    91992.0       135495.00    252665.000000
14   119943.0       156547.00    256513.000000
15   114524.0       122617.00    261776.000000
16    78013.0       121598.00    264346.000000
17    94657.0       145078.00    282574.000000
18    91749.0       114176.00    294920.000000
19    86420.0       153514.00         0.000000
20    76254.0       113867.00    298664.000000
21    78389.0       153773.00    299737.000000
22    73995.0       122783.00    303319.000000
23    67533.0       105751.00    304769.000000
24    77044.0        99281.00    140575.000000
25    64665.0       139553.00    137963.000000
26    75329.0       144136.00    134050.000000
27    72108.0       127865.00    353184.000000
28    66052.0       182646.00    118148.000000
29    65605.0       153032.00    107138.000000
30    61994.0       115641.00     91131.000000
31    61136.0       152702.00     88218.000000
32    63409.0       129220.00     46085.000000
33    55494.0       103057.00    214635.000000
34    46426.0       157694.00    210798.000000
35    46014.0        85047.00    205518.000000
36    28664.0       127056.00    201127.000000
37    44070.0        51283.00    197029.000000
38    20230.0        65948.00    185265.000000
39    38559.0        82982.00    174999.000000
40    28754.0       118546.00    172796.000000
41    27893.0        84711.00    164471.000000
42    23641.0        96190.00    148001.000000
43    15506.0       127382.00     35534.000000
44    22178.0       154806.00     28335.000000
45     1000.0       124153.00      1904.000000
46     1315.0       115816.00    297114.000000
47        0.0       135427.00         0.000000
48      542.0        51743.00         0.000000
49        0.0       116984.00    214409.836735

In [21]:
#Use last 3 rows to build a model and use the first for the prediction
x = df1.iloc[0:4,0:2]
x

   R&D Spend  Administration
0   165349.0       136898.00
1        NaN       151378.00
2   153442.0       101146.00
3   144372.0           11.06

In [22]:
y = df1.iloc[[0,1,2,4],1]
y

0    136898.0
1    151378.0
2    101146.0
4     91392.0
Name: Administration, dtype: float64